C$PROG LEXT
      FUNCTION LEXT(IBY,IA,IB)
C
      BYTE IBY(1)
C
C     LOCATES DOT - FIRST BYTE OF FILENAME EXTENSION
C
      LDOT=0
      LBRA=0
C
      DO 10 I=IA,IB
      IF(IBY(I).EQ.'2E'X) LDOT=I  !LOCATION OF  .
      IF(IBY(I).EQ.'5D'X) LBRA=I  !LOCATION OF  ]
   10 CONTINUE
C
      IF(LBRA.GT.LDOT)    LDOT=0
      LEXT=LDOT
      RETURN
      END
