C$PROG LOCID
      FUNCTION LOCID(IDIR,ILO,IHI,IDN)
      INTEGER*4 IDIR(1)
C
C     FUNCTION TO SEARCH "SPKIO DIRECTORY" FOR ID NUMBERS
C
      IF(IHI.LT.ILO) GO TO 15
      N=2*ILO+1
      DO 10 I=ILO,IHI
      N=N+2
      IF(IDIR(N).EQ.IDN) GO TO 20
   10 CONTINUE
   15 N=0
   20 LOCID=N
      RETURN
      END
