C$PROG LODUP
      SUBROUTINE LODUP(IBY,IA,IB,JBY,JA)
      BYTE IBY(1),JBY(1)
C
C     LOADS BYTES IA THRU IB FROM IBY INTO JBY (STARTING AT JA IN JBY)
C
      J=JA
      DO 10 I=IA,IB
      JBY(J)=IBY(I)
      J=J+1
   10 CONTINUE
      RETURN
      END
