#!/bin/tcsh
cd /user/schiller/osloware/mama/src/libs/gf2
make -f Makefile all
cd /user/schiller/osloware/mama/src/libs/milib
make -f Makefile all
cd /user/schiller/osloware/mama/src/libs/minig_x
make -f Makefile all
cd /user/schiller/osloware/mama/src/libs/util
make -f Makefile all
cd /user/schiller/osloware/mama/src
make -f Makefile all
exit 0
