#!/bin/tcsh
cd /user/schiller/osloware/mama/spy/libs/graph
make -f Makefile all
cd /user/schiller/osloware/mama/spy/libs/spyfiles
make -f Makefile all
cd /user/schiller/osloware/mama/spy
make -f Makefile all
exit 0
