#!/bin/tcsh
cd /user/schiller/osloware/mama/src/libs/gf2
make -f Makefile all
cd /user/schiller/osloware/mama/src/libs/milib
make -f Makefile all
cd /user/schiller/osloware/mama/src/libs/minig_x
make -f Makefile all
cd /user/schiller/osloware/mama/src/libs/util
make -f Makefile all
cd /user/schiller/osloware/mama/src
make -f Makefile all
cd /user/schiller/osloware/mama/spy/libs/graph
make -f Makefile all
cd /user/schiller/osloware/mama/spy/libs/spyfiles
make -f Makefile all
cd /user/schiller/osloware/mama/spy
make -f Makefile all
cd /user/schiller/osloware/mama/update/libs/graph
make -f Makefile all
cd /user/schiller/osloware/mama/update/libs/upfiles
make -f Makefile all
cd /user/schiller/osloware/mama/update
make -f Makefile all
cd /user/schiller/osloware/offline/src
make -f Makefile all
cd /user/schiller/osloware/reduc/src/
make -f Makefile all
cd /user/schiller/osloware/magprogs
make -f Makefile all
cd /user/schiller/osloware/programs
make -f Makefile all
