//
// File generated by rootcint at Thu Dec  4 13:49:58 2014

// Do NOT change. Changes will be lost next time file is generated
//

#define R__DICTIONARY_FILENAME rootdict
#include "RConfig.h" //rootcint 4834
#if !defined(R__ACCESS_IN_SYMBOL)
//Break the privacy of classes -- Disabled for the moment
#define private public
#define protected public
#endif

// Since CINT ignores the std namespace, we need to do so in this file.
namespace std {} using namespace std;
#include "rootdict.h"

#include "TClass.h"
#include "TBuffer.h"
#include "TMemberInspector.h"
#include "TInterpreter.h"
#include "TVirtualMutex.h"
#include "TError.h"

#ifndef G__ROOT
#define G__ROOT
#endif

#include "RtypesImp.h"
#include "TIsAProxy.h"
#include "TFileMergeInfo.h"

// Direct notice to TROOT of the dictionary's loading.
namespace {
   static struct DictInit {
      DictInit() {
         ROOT::RegisterModule();
      }
   } __TheDictionaryInitializer;
}

// START OF SHADOWS

namespace ROOT {
   namespace Shadow {
   } // of namespace Shadow
} // of namespace ROOT
// END OF SHADOWS

namespace ROOT {
   void MyMainFrame_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void *new_MyMainFrame(void *p = 0);
   static void *newArray_MyMainFrame(Long_t size, void *p);
   static void delete_MyMainFrame(void *p);
   static void deleteArray_MyMainFrame(void *p);
   static void destruct_MyMainFrame(void *p);
   static void streamer_MyMainFrame(TBuffer &buf, void *obj);

   // Function generating the singleton type initializer
   static TGenericClassInfo *GenerateInitInstanceLocal(const ::MyMainFrame*)
   {
      ::MyMainFrame *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TInstrumentedIsAProxy< ::MyMainFrame >(0);
      static ::ROOT::TGenericClassInfo 
         instance("MyMainFrame", ::MyMainFrame::Class_Version(), "./rkinz.h", 21,
                  typeid(::MyMainFrame), DefineBehavior(ptr, ptr),
                  &::MyMainFrame::Dictionary, isa_proxy, 0,
                  sizeof(::MyMainFrame) );
      instance.SetNew(&new_MyMainFrame);
      instance.SetNewArray(&newArray_MyMainFrame);
      instance.SetDelete(&delete_MyMainFrame);
      instance.SetDeleteArray(&deleteArray_MyMainFrame);
      instance.SetDestructor(&destruct_MyMainFrame);
      instance.SetStreamerFunc(&streamer_MyMainFrame);
      return &instance;
   }
   TGenericClassInfo *GenerateInitInstance(const ::MyMainFrame*)
   {
      return GenerateInitInstanceLocal((::MyMainFrame*)0);
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const ::MyMainFrame*)0x0); R__UseDummy(_R__UNIQUE_(Init));
} // end of namespace ROOT

//______________________________________________________________________________
atomic_TClass_ptr MyMainFrame::fgIsA(0);  // static to hold class pointer

//______________________________________________________________________________
const char *MyMainFrame::Class_Name()
{
   return "MyMainFrame";
}

//______________________________________________________________________________
const char *MyMainFrame::ImplFileName()
{
   return ::ROOT::GenerateInitInstanceLocal((const ::MyMainFrame*)0x0)->GetImplFileName();
}

//______________________________________________________________________________
int MyMainFrame::ImplFileLine()
{
   return ::ROOT::GenerateInitInstanceLocal((const ::MyMainFrame*)0x0)->GetImplFileLine();
}

//______________________________________________________________________________
void MyMainFrame::Dictionary()
{
   fgIsA = ::ROOT::GenerateInitInstanceLocal((const ::MyMainFrame*)0x0)->GetClass();
}

//______________________________________________________________________________
TClass *MyMainFrame::Class()
{
   if (!fgIsA) { R__LOCKGUARD2(gCINTMutex); if(!fgIsA) {fgIsA = ::ROOT::GenerateInitInstanceLocal((const ::MyMainFrame*)0x0)->GetClass();} }
   return fgIsA;
}

//______________________________________________________________________________
void MyMainFrame::Streamer(TBuffer &R__b)
{
   // Stream an object of class MyMainFrame.

   TGMainFrame::Streamer(R__b);
}

//______________________________________________________________________________
void MyMainFrame::ShowMembers(TMemberInspector &R__insp)
{
      // Inspect the data members of an object of class MyMainFrame.
      TClass *R__cl = ::MyMainFrame::IsA();
      if (R__cl || R__insp.IsA()) { }
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*cmb_beam", &cmb_beam);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*n_energy", &n_energy);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*n_targetA", &n_targetA);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*n_targetZ", &n_targetZ);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*n_targetT", &n_targetT);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*n_targetT_C12", &n_targetT_C12);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*n_det", &n_det);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*r_c12", &r_c12);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*r_anytarget", &r_anytarget);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*r_forward", &r_forward);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*r_backward", &r_backward);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*ecanvas", &ecanvas);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*statusbar", &statusbar);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*t_targetName", &t_targetName);
      TGMainFrame::ShowMembers(R__insp);
}

namespace ROOT {
   // Wrappers around operator new
   static void *new_MyMainFrame(void *p) {
      return  p ? new(p) ::MyMainFrame : new ::MyMainFrame;
   }
   static void *newArray_MyMainFrame(Long_t nElements, void *p) {
      return p ? new(p) ::MyMainFrame[nElements] : new ::MyMainFrame[nElements];
   }
   // Wrapper around operator delete
   static void delete_MyMainFrame(void *p) {
      delete ((::MyMainFrame*)p);
   }
   static void deleteArray_MyMainFrame(void *p) {
      delete [] ((::MyMainFrame*)p);
   }
   static void destruct_MyMainFrame(void *p) {
      typedef ::MyMainFrame current_t;
      ((current_t*)p)->~current_t();
   }
   // Wrapper around a custom streamer member function.
   static void streamer_MyMainFrame(TBuffer &buf, void *obj) {
      ((::MyMainFrame*)obj)->::MyMainFrame::Streamer(buf);
   }
} // end of namespace ROOT for class ::MyMainFrame

/********************************************************
* rootdict.cpp
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************/

#ifdef G__MEMTEST
#undef malloc
#undef free
#endif

#if defined(__GNUC__) && __GNUC__ >= 4 && ((__GNUC_MINOR__ == 2 && __GNUC_PATCHLEVEL__ >= 1) || (__GNUC_MINOR__ >= 3))
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif

extern "C" void G__cpp_reset_tagtablerootdict();

extern "C" void G__set_cpp_environmentrootdict() {
  G__add_compiledheader("TObject.h");
  G__add_compiledheader("TMemberInspector.h");
  G__add_compiledheader("rkinz.h");
  G__cpp_reset_tagtablerootdict();
}
#include <new>
extern "C" int G__cpp_dllrevrootdict() { return(30051515); }

/*********************************************************
* Member function Interface Method
*********************************************************/

/* MyMainFrame */
static int G__rootdict_312_0_1(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   MyMainFrame* p = NULL;
   char* gvp = (char*) G__getgvp();
   int n = G__getaryconstruct();
   if (n) {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new MyMainFrame[n];
     } else {
       p = new((void*) gvp) MyMainFrame[n];
     }
   } else {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new MyMainFrame;
     } else {
       p = new((void*) gvp) MyMainFrame;
     }
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__rootdictLN_MyMainFrame));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__rootdict_312_0_3(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((MyMainFrame*) G__getstructoffset())->OnComboBeamSelect((Int_t) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__rootdict_312_0_4(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((MyMainFrame*) G__getstructoffset())->OnDetectorsForward();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__rootdict_312_0_5(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((MyMainFrame*) G__getstructoffset())->OnDetectorsBackward();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__rootdict_312_0_6(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((MyMainFrame*) G__getstructoffset())->OnTarget12C();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__rootdict_312_0_7(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((MyMainFrame*) G__getstructoffset())->OnTargetAny();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__rootdict_312_0_8(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((MyMainFrame*) G__getstructoffset())->OnTargetZ((Long_t) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__rootdict_312_0_9(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((MyMainFrame*) G__getstructoffset())->OnTargetZText((const char*) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__rootdict_312_0_10(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((MyMainFrame*) G__getstructoffset())->OnCanvasEvent((Int_t) G__int(libp->para[0]), (Int_t) G__int(libp->para[1])
, (Int_t) G__int(libp->para[2]), (TObject*) G__int(libp->para[3]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__rootdict_312_0_11(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((MyMainFrame*) G__getstructoffset())->OnButtonCalc();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__rootdict_312_0_14(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) MyMainFrame::Class());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__rootdict_312_0_15(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) MyMainFrame::Class_Name());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__rootdict_312_0_16(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 115, (long) MyMainFrame::Class_Version());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__rootdict_312_0_17(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      MyMainFrame::Dictionary();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__rootdict_312_0_21(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((MyMainFrame*) G__getstructoffset())->StreamerNVirtual(*(TBuffer*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__rootdict_312_0_22(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) MyMainFrame::DeclFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__rootdict_312_0_23(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) MyMainFrame::ImplFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__rootdict_312_0_24(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) MyMainFrame::ImplFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__rootdict_312_0_25(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) MyMainFrame::DeclFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef MyMainFrame G__TMyMainFrame;
static int G__rootdict_312_0_26(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   char* gvp = (char*) G__getgvp();
   long soff = G__getstructoffset();
   int n = G__getaryconstruct();
   //
   //has_a_delete: 1
   //has_own_delete1arg: 0
   //has_own_delete2arg: 0
   //
   if (!soff) {
     return(1);
   }
   if (n) {
     if (gvp == (char*)G__PVOID) {
       delete[] (MyMainFrame*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       for (int i = n - 1; i >= 0; --i) {
         ((MyMainFrame*) (soff+(sizeof(MyMainFrame)*i)))->~G__TMyMainFrame();
       }
       G__setgvp((long)gvp);
     }
   } else {
     if (gvp == (char*)G__PVOID) {
       delete (MyMainFrame*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       ((MyMainFrame*) (soff))->~G__TMyMainFrame();
       G__setgvp((long)gvp);
     }
   }
   G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}


/* Setting up global function */

/*********************************************************
* Member function Stub
*********************************************************/

/* MyMainFrame */

/*********************************************************
* Global function Stub
*********************************************************/

/*********************************************************
* Get size of pointer to member function
*********************************************************/
class G__Sizep2memfuncrootdict {
 public:
  G__Sizep2memfuncrootdict(): p(&G__Sizep2memfuncrootdict::sizep2memfunc) {}
    size_t sizep2memfunc() { return(sizeof(p)); }
  private:
    size_t (G__Sizep2memfuncrootdict::*p)();
};

size_t G__get_sizep2memfuncrootdict()
{
  G__Sizep2memfuncrootdict a;
  G__setsizep2memfunc((int)a.sizep2memfunc());
  return((size_t)a.sizep2memfunc());
}


/*********************************************************
* virtual base class offset calculation interface
*********************************************************/

   /* Setting up class inheritance */

/*********************************************************
* Inheritance information setup/
*********************************************************/
extern "C" void G__cpp_setup_inheritancerootdict() {

   /* Setting up class inheritance */
   if(0==G__getnumbaseclass(G__get_linked_tagnum(&G__rootdictLN_MyMainFrame))) {
     MyMainFrame *G__Lderived;
     G__Lderived=(MyMainFrame*)0x1000;
     {
       TGMainFrame *G__Lpbase=(TGMainFrame*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__rootdictLN_MyMainFrame),G__get_linked_tagnum(&G__rootdictLN_TGMainFrame),(long)G__Lpbase-(long)G__Lderived,1,1);
     }
     {
       TGCompositeFrame *G__Lpbase=(TGCompositeFrame*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__rootdictLN_MyMainFrame),G__get_linked_tagnum(&G__rootdictLN_TGCompositeFrame),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
     {
       TGFrame *G__Lpbase=(TGFrame*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__rootdictLN_MyMainFrame),G__get_linked_tagnum(&G__rootdictLN_TGFrame),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
     {
       TGWindow *G__Lpbase=(TGWindow*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__rootdictLN_MyMainFrame),G__get_linked_tagnum(&G__rootdictLN_TGWindow),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
     {
       TGObject *G__Lpbase=(TGObject*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__rootdictLN_MyMainFrame),G__get_linked_tagnum(&G__rootdictLN_TGObject),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
     {
       TObject *G__Lpbase=(TObject*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__rootdictLN_MyMainFrame),G__get_linked_tagnum(&G__rootdictLN_TObject),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
     {
       TQObject *G__Lpbase=(TQObject*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__rootdictLN_MyMainFrame),G__get_linked_tagnum(&G__rootdictLN_TQObject),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
   }
}

/*********************************************************
* typedef information setup/
*********************************************************/
extern "C" void G__cpp_setup_typetablerootdict() {

   /* Setting up typedef entry */
   G__search_typename2("Int_t",105,-1,0,-1);
   G__setnewtype(-1,"Signed integer 4 bytes (int)",0);
   G__search_typename2("Long_t",108,-1,0,-1);
   G__setnewtype(-1,"Signed long integer 8 bytes (long)",0);
   G__search_typename2("Version_t",115,-1,0,-1);
   G__setnewtype(-1,"Class version identifier (short)",0);
   G__search_typename2("vector<ROOT::TSchemaHelper>",117,G__get_linked_tagnum(&G__rootdictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__rootdictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__rootdictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__rootdictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__rootdictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TVirtualArray*>",117,G__get_linked_tagnum(&G__rootdictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__rootdictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__rootdictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__rootdictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__rootdictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("pair<UInt_t,Int_t>",117,G__get_linked_tagnum(&G__rootdictLN_pairlEunsignedsPintcOintgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<std::pair<UInt_t,Int_t> >",117,G__get_linked_tagnum(&G__rootdictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<pair<UInt_t,Int_t> >",117,G__get_linked_tagnum(&G__rootdictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__rootdictLN_reverse_iteratorlEvectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__rootdictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__rootdictLN_reverse_iteratorlEvectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__rootdictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<pair<unsigned int,int> >",117,G__get_linked_tagnum(&G__rootdictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<std::bidirectional_iterator_tag,TObject*,std::ptrdiff_t,const TObject**,const TObject*&>",117,G__get_linked_tagnum(&G__rootdictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,std::ptrdiff_t,const TObject**,const TObject*&>",117,G__get_linked_tagnum(&G__rootdictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*>",117,G__get_linked_tagnum(&G__rootdictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,long>",117,G__get_linked_tagnum(&G__rootdictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,long,const TObject**>",117,G__get_linked_tagnum(&G__rootdictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
}

/*********************************************************
* Data Member information setup/
*********************************************************/

   /* Setting up class,struct,union tag member variable */

   /* MyMainFrame */
static void G__setup_memvarMyMainFrame(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__rootdictLN_MyMainFrame));
   { MyMainFrame *p; p=(MyMainFrame*)0x1000; if (p) { }
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__rootdictLN_TClass),G__defined_typename("atomic_TClass_ptr"),-2,4,"fgIsA=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__rootdictLN_TGComboBox),-1,-1,4,"cmb_beam=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__rootdictLN_TGNumberEntry),-1,-1,4,"n_energy=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__rootdictLN_TGNumberEntry),-1,-1,4,"n_targetA=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__rootdictLN_TGNumberEntry),-1,-1,4,"n_targetZ=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__rootdictLN_TGNumberEntry),-1,-1,4,"n_targetT=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__rootdictLN_TGNumberEntry),-1,-1,4,"n_targetT_C12=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__rootdictLN_TGNumberEntry),-1,-1,4,"n_det=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__rootdictLN_TGRadioButton),-1,-1,4,"r_c12=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__rootdictLN_TGRadioButton),-1,-1,4,"r_anytarget=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__rootdictLN_TGRadioButton),-1,-1,4,"r_forward=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__rootdictLN_TGRadioButton),-1,-1,4,"r_backward=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__rootdictLN_TRootEmbeddedCanvas),-1,-1,4,"ecanvas=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__rootdictLN_TGStatusBar),-1,-1,4,"statusbar=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__rootdictLN_TGTextEntry),-1,-1,4,"t_targetName=",0,(char*)NULL);
   }
   G__tag_memvar_reset();
}

extern "C" void G__cpp_setup_memvarrootdict() {
}
/***********************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
***********************************************************/

/*********************************************************
* Member function information setup for each class
*********************************************************/
static void G__setup_memfuncMyMainFrame(void) {
   /* MyMainFrame */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__rootdictLN_MyMainFrame));
   G__memfunc_setup("MyMainFrame",1078,G__rootdict_312_0_1, 105, G__get_linked_tagnum(&G__rootdictLN_MyMainFrame), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("CloseWindow",1134,(G__InterfaceMethod) NULL,121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("OnComboBeamSelect",1666,G__rootdict_312_0_3, 121, -1, -1, 0, 1, 1, 1, 0, "i - 'Int_t' 0 - -", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("OnDetectorsForward",1855,G__rootdict_312_0_4, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("OnDetectorsBackward",1929,G__rootdict_312_0_5, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("OnTarget12C",970,G__rootdict_312_0_6, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("OnTargetAny",1100,G__rootdict_312_0_7, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("OnTargetZ",894,G__rootdict_312_0_8, 121, -1, -1, 0, 1, 1, 1, 0, "l - 'Long_t' 0 - -", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("OnTargetZText",1315,G__rootdict_312_0_9, 121, -1, -1, 0, 1, 1, 1, 0, "C - - 10 - -", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("OnCanvasEvent",1307,G__rootdict_312_0_10, 121, -1, -1, 0, 4, 1, 1, 0, 
"i - 'Int_t' 0 - event i - 'Int_t' 0 - x "
"i - 'Int_t' 0 - y U 'TObject' - 0 - obj", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("OnButtonCalc",1196,G__rootdict_312_0_11, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("LoadDefaults",1208,(G__InterfaceMethod) NULL, 121, -1, -1, 0, 0, 1, 4, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SaveDefaults",1223,(G__InterfaceMethod) NULL, 121, -1, -1, 0, 0, 1, 4, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Class",502,G__rootdict_312_0_14, 85, G__get_linked_tagnum(&G__rootdictLN_TClass), -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (TClass* (*)())(&MyMainFrame::Class) ), 0);
   G__memfunc_setup("Class_Name",982,G__rootdict_312_0_15, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&MyMainFrame::Class_Name) ), 0);
   G__memfunc_setup("Class_Version",1339,G__rootdict_312_0_16, 115, -1, G__defined_typename("Version_t"), 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (Version_t (*)())(&MyMainFrame::Class_Version) ), 0);
   G__memfunc_setup("Dictionary",1046,G__rootdict_312_0_17, 121, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (void (*)())(&MyMainFrame::Dictionary) ), 0);
   G__memfunc_setup("IsA",253,(G__InterfaceMethod) NULL,85, G__get_linked_tagnum(&G__rootdictLN_TClass), -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("ShowMembers",1132,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TMemberInspector' - 1 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Streamer",835,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("StreamerNVirtual",1656,G__rootdict_312_0_21, 121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - ClassDef_StreamerNVirtual_b", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DeclFileName",1145,G__rootdict_312_0_22, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&MyMainFrame::DeclFileName) ), 0);
   G__memfunc_setup("ImplFileLine",1178,G__rootdict_312_0_23, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&MyMainFrame::ImplFileLine) ), 0);
   G__memfunc_setup("ImplFileName",1171,G__rootdict_312_0_24, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&MyMainFrame::ImplFileName) ), 0);
   G__memfunc_setup("DeclFileLine",1152,G__rootdict_312_0_25, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&MyMainFrame::DeclFileLine) ), 0);
   // automatic destructor
   G__memfunc_setup("~MyMainFrame", 1204, G__rootdict_312_0_26, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 1);
   G__tag_memfunc_reset();
}


/*********************************************************
* Member function information setup
*********************************************************/
extern "C" void G__cpp_setup_memfuncrootdict() {
}

/*********************************************************
* Global variable information setup for each class
*********************************************************/
static void G__cpp_setup_global0() {

   /* Setting up global variables */
   G__resetplocal();

}

static void G__cpp_setup_global1() {
}

static void G__cpp_setup_global2() {
}

static void G__cpp_setup_global3() {
}

static void G__cpp_setup_global4() {
}

static void G__cpp_setup_global5() {

   G__resetglobalenv();
}
extern "C" void G__cpp_setup_globalrootdict() {
  G__cpp_setup_global0();
  G__cpp_setup_global1();
  G__cpp_setup_global2();
  G__cpp_setup_global3();
  G__cpp_setup_global4();
  G__cpp_setup_global5();
}

/*********************************************************
* Global function information setup for each class
*********************************************************/
static void G__cpp_setup_func0() {
   G__lastifuncposition();

}

static void G__cpp_setup_func1() {
}

static void G__cpp_setup_func2() {
}

static void G__cpp_setup_func3() {
}

static void G__cpp_setup_func4() {
}

static void G__cpp_setup_func5() {
}

static void G__cpp_setup_func6() {
}

static void G__cpp_setup_func7() {
}

static void G__cpp_setup_func8() {
}

static void G__cpp_setup_func9() {
}

static void G__cpp_setup_func10() {
}

static void G__cpp_setup_func11() {
}

static void G__cpp_setup_func12() {
}

static void G__cpp_setup_func13() {
}

static void G__cpp_setup_func14() {

   G__resetifuncposition();
}

extern "C" void G__cpp_setup_funcrootdict() {
  G__cpp_setup_func0();
  G__cpp_setup_func1();
  G__cpp_setup_func2();
  G__cpp_setup_func3();
  G__cpp_setup_func4();
  G__cpp_setup_func5();
  G__cpp_setup_func6();
  G__cpp_setup_func7();
  G__cpp_setup_func8();
  G__cpp_setup_func9();
  G__cpp_setup_func10();
  G__cpp_setup_func11();
  G__cpp_setup_func12();
  G__cpp_setup_func13();
  G__cpp_setup_func14();
}

/*********************************************************
* Class,struct,union,enum tag information setup
*********************************************************/
/* Setup class/struct taginfo */
G__linked_taginfo G__rootdictLN_TClass = { "TClass" , 99 , -1 };
G__linked_taginfo G__rootdictLN_TBuffer = { "TBuffer" , 99 , -1 };
G__linked_taginfo G__rootdictLN_TMemberInspector = { "TMemberInspector" , 99 , -1 };
G__linked_taginfo G__rootdictLN_TObject = { "TObject" , 99 , -1 };
G__linked_taginfo G__rootdictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR = { "vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >" , 99 , -1 };
G__linked_taginfo G__rootdictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR = { "reverse_iterator<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::iterator>" , 99 , -1 };
G__linked_taginfo G__rootdictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR = { "vector<TVirtualArray*,allocator<TVirtualArray*> >" , 99 , -1 };
G__linked_taginfo G__rootdictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TVirtualArray*,allocator<TVirtualArray*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__rootdictLN_TGObject = { "TGObject" , 99 , -1 };
G__linked_taginfo G__rootdictLN_TQObject = { "TQObject" , 99 , -1 };
G__linked_taginfo G__rootdictLN_TGWindow = { "TGWindow" , 99 , -1 };
G__linked_taginfo G__rootdictLN_pairlEunsignedsPintcOintgR = { "pair<unsigned int,int>" , 115 , -1 };
G__linked_taginfo G__rootdictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR = { "vector<pair<unsigned int,int>,allocator<pair<unsigned int,int> > >" , 99 , -1 };
G__linked_taginfo G__rootdictLN_reverse_iteratorlEvectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<pair<unsigned int,int>,allocator<pair<unsigned int,int> > >::iterator>" , 99 , -1 };
G__linked_taginfo G__rootdictLN_TGFrame = { "TGFrame" , 99 , -1 };
G__linked_taginfo G__rootdictLN_TGCompositeFrame = { "TGCompositeFrame" , 99 , -1 };
G__linked_taginfo G__rootdictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR = { "iterator<bidirectional_iterator_tag,TObject*,long,const TObject**,const TObject*&>" , 115 , -1 };
G__linked_taginfo G__rootdictLN_TGMainFrame = { "TGMainFrame" , 99 , -1 };
G__linked_taginfo G__rootdictLN_TGComboBox = { "TGComboBox" , 99 , -1 };
G__linked_taginfo G__rootdictLN_TGNumberEntry = { "TGNumberEntry" , 99 , -1 };
G__linked_taginfo G__rootdictLN_TGRadioButton = { "TGRadioButton" , 99 , -1 };
G__linked_taginfo G__rootdictLN_TGStatusBar = { "TGStatusBar" , 99 , -1 };
G__linked_taginfo G__rootdictLN_TGTextEntry = { "TGTextEntry" , 99 , -1 };
G__linked_taginfo G__rootdictLN_TRootEmbeddedCanvas = { "TRootEmbeddedCanvas" , 99 , -1 };
G__linked_taginfo G__rootdictLN_MyMainFrame = { "MyMainFrame" , 99 , -1 };

/* Reset class/struct taginfo */
extern "C" void G__cpp_reset_tagtablerootdict() {
  G__rootdictLN_TClass.tagnum = -1 ;
  G__rootdictLN_TBuffer.tagnum = -1 ;
  G__rootdictLN_TMemberInspector.tagnum = -1 ;
  G__rootdictLN_TObject.tagnum = -1 ;
  G__rootdictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR.tagnum = -1 ;
  G__rootdictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__rootdictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR.tagnum = -1 ;
  G__rootdictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__rootdictLN_TGObject.tagnum = -1 ;
  G__rootdictLN_TQObject.tagnum = -1 ;
  G__rootdictLN_TGWindow.tagnum = -1 ;
  G__rootdictLN_pairlEunsignedsPintcOintgR.tagnum = -1 ;
  G__rootdictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR.tagnum = -1 ;
  G__rootdictLN_reverse_iteratorlEvectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__rootdictLN_TGFrame.tagnum = -1 ;
  G__rootdictLN_TGCompositeFrame.tagnum = -1 ;
  G__rootdictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR.tagnum = -1 ;
  G__rootdictLN_TGMainFrame.tagnum = -1 ;
  G__rootdictLN_TGComboBox.tagnum = -1 ;
  G__rootdictLN_TGNumberEntry.tagnum = -1 ;
  G__rootdictLN_TGRadioButton.tagnum = -1 ;
  G__rootdictLN_TGStatusBar.tagnum = -1 ;
  G__rootdictLN_TGTextEntry.tagnum = -1 ;
  G__rootdictLN_TRootEmbeddedCanvas.tagnum = -1 ;
  G__rootdictLN_MyMainFrame.tagnum = -1 ;
}


extern "C" void G__cpp_setup_tagtablerootdict() {

   /* Setting up class,struct,union tag entry */
   G__get_linked_tagnum_fwd(&G__rootdictLN_TClass);
   G__get_linked_tagnum_fwd(&G__rootdictLN_TBuffer);
   G__get_linked_tagnum_fwd(&G__rootdictLN_TMemberInspector);
   G__get_linked_tagnum_fwd(&G__rootdictLN_TObject);
   G__get_linked_tagnum_fwd(&G__rootdictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR);
   G__get_linked_tagnum_fwd(&G__rootdictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__rootdictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR);
   G__get_linked_tagnum_fwd(&G__rootdictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__rootdictLN_TGObject);
   G__get_linked_tagnum_fwd(&G__rootdictLN_TQObject);
   G__get_linked_tagnum_fwd(&G__rootdictLN_TGWindow);
   G__get_linked_tagnum_fwd(&G__rootdictLN_pairlEunsignedsPintcOintgR);
   G__get_linked_tagnum_fwd(&G__rootdictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__rootdictLN_reverse_iteratorlEvectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__rootdictLN_TGFrame);
   G__get_linked_tagnum_fwd(&G__rootdictLN_TGCompositeFrame);
   G__get_linked_tagnum_fwd(&G__rootdictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR);
   G__get_linked_tagnum_fwd(&G__rootdictLN_TGMainFrame);
   G__get_linked_tagnum_fwd(&G__rootdictLN_TGComboBox);
   G__get_linked_tagnum_fwd(&G__rootdictLN_TGNumberEntry);
   G__get_linked_tagnum_fwd(&G__rootdictLN_TGRadioButton);
   G__get_linked_tagnum_fwd(&G__rootdictLN_TGStatusBar);
   G__get_linked_tagnum_fwd(&G__rootdictLN_TGTextEntry);
   G__get_linked_tagnum_fwd(&G__rootdictLN_TRootEmbeddedCanvas);
   G__tagtable_setup(G__get_linked_tagnum_fwd(&G__rootdictLN_MyMainFrame),sizeof(MyMainFrame),-1,62720,(char*)NULL,G__setup_memvarMyMainFrame,G__setup_memfuncMyMainFrame);
}
extern "C" void G__cpp_setuprootdict(void) {
  G__check_setup_version(30051515,"G__cpp_setuprootdict()");
  G__set_cpp_environmentrootdict();
  G__cpp_setup_tagtablerootdict();

  G__cpp_setup_inheritancerootdict();

  G__cpp_setup_typetablerootdict();

  G__cpp_setup_memvarrootdict();

  G__cpp_setup_memfuncrootdict();
  G__cpp_setup_globalrootdict();
  G__cpp_setup_funcrootdict();

   if(0==G__getsizep2memfunc()) G__get_sizep2memfuncrootdict();
  return;
}
class G__cpp_setup_initrootdict {
  public:
    G__cpp_setup_initrootdict() { G__add_setup_func("rootdict",(G__incsetup)(&G__cpp_setuprootdict)); G__call_setup_funcs(); }
   ~G__cpp_setup_initrootdict() { G__remove_setup_func("rootdict"); }
};
G__cpp_setup_initrootdict G__cpp_setup_initializerrootdict;

