



100 REM    MATTERS.BAS        NOVEMBER 20, 1991      J. KANTELE

110 COLOR 15, 1: CLS

120 PRINT "******************************************************************"

130 PRINT

140 PRINT " LIST OF DENSITIES AND SOME OTHER PROPERTIES OF MATERIALS "

150 PRINT

160 PRINT "******************************************************************"

170 GOTO 180

180 COLOR 14, 4: CLS

190 PRINT

200 PRINT "  MATERIAL (Z)   DENSITY (g/cm^3)   MATERIAL (Z)   DENSITY (g/cm^3)  "

210 PRINT "    Be (4)            1.85             Cd (48)           8.65        "

220 PRINT "    Graphite (6)      2.25             Sn (50)           7.28 (5.75) "

230 PRINT "    NE Plastic (6)    1.03             Sb (51)           6.69        "

240 PRINT "    Al (13)           2.70             Te (52)           6.24        "

250 PRINT "    Si (14)           2.33             Ta (73)          16.6         "

260 PRINT "    Fe (26)           7.87             W  (74)          19.3         "

270 PRINT "    Ni (28)           8.9              Pt (78)          21.45        "

280 PRINT "    Cu (29)           8.96             Au (79)          19.3         "

290 PRINT "    Ge (32)           5.32             Pb (82)          11.34        "

300 PRINT "    Pd (46)          12.0              Bi (83)           9.75        "

310 PRINT "    Ag (47)          10.5              U  (92)          18.9         "

320 PRINT " -----------------------------------------------------------------"

330 PRINT "    SOME COMPOUNDS:      MASS FRACTIONS      DENSITY (g/cm^3) "

340 PRINT "    Paraffin (CnH2n+2)      .8, .2                 .85 "

350 PRINT "    Lucite (C5H8O2)n    .60, .08, .32          1.18 - 1.19"

360 PRINT "    Glass (Si02 etc)       <.5, <.5                2.5 "

370 PRINT "    NaI (11, 53)          .153, .847               3.67 "

380 PRINT "    BaF2 (56,9)           .783, .217               4.89  "

390 PRINT "    BGO (Bi4Ge3O12)     .671, .175, .154           7.13  "

400 PRINT "    Hevimet (W,Ni,Cu)    .9, .075, .025            17  "

410 PRINT " *******************************************************************"

420 COLOR 15, 1, 1

430 END



